sudo: true
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

node_js:
  - "6"
  - "7"
  - "node"

matrix:
  fast_finish: true

before_install:
  - npm install npm@5 -g
  - npm cache verify
  - npm prune
  - npm update

install:
  - npm install

script:
  - npm start
